import random

JSON_SITES_DATA = "dataset/sites2.json"
JSON_VIGILANTES_DATA = "dataset/vigilantes3.json"
MAX_TOTAL_WEEKS = 4
WINDOWS_RANDOM_THE_VIGILANTS_ORDER_FOR_SITE = 5
SEED = 0
SETTINGS=random.seed(SEED)
MISSING_FITNESS_VALUE = 10
ASSIGNED_VIGILANTES_FITNESS_VALUE = 10
DISTANCE_FITNESS_VALUE= 1
EXTRA_HOURS_FITNESS_VALUE = 1
