import random
JSON_SITES_DATA = "dataset/sites2.json"
JSON_VIGILANTES_DATA = "dataset/vigilantes.json"
MAX_TOTAL_WEEKS = 2
WINDOWS_RANDOM_THE_VIGILANTS_ORDER_FOR_SITE = 10
SEED = 0
SETTINGS=random.seed(SEED)
MISSING_FITNESS_VALUE = 10000
ASSIGNED_VIGILANTES_FITNESS_VALUE = 50000
DISTANCE_FITNESS_VALUE = 100
EXTRA_HOURS_FITNESS_VALUE = 500
RESTRICTED_LIST_AMOUNT_COMPONENT:int = 10 
#NUMBER ITERACTION FOR THA SELECCION OF RANDOM COMPONENTE IN THE CROOSIN
NUMBER_ITERATION_SELECTION_COMPONENTE = 10