import random
JSON_SITES_DATA = "app/dataset/sites.json"
JSON_VIGILANTES_DATA = "app/dataset/vigilantes.json"
MAX_TOTAL_WEEKS = 4
WINDOWS_RANDOM_THE_VIGILANTS_ORDER_FOR_SITE = 5
SEED = 0
SETTINGS=random.seed(SEED)
MISSING_FITNESS_VALUE = 100
ASSIGNED_VIGILANTES_FITNESS_VALUE = 20
DISTANCE_FITNESS_VALUE= 1
EXTRA_HOURS_FITNESS_VALUE = 5
#NUMBER ITERACTION FOR THA SELECCION OF RANDOM COMPONENTE IN THE CROOSIN
#NSGA2 
NUM_OBJECTIVE = 4 # 0 -3 = 4 objetive
MAX_EFOS = 2
NUM_SOLUTION=4
NUMBER_OF_CHILDREN_GENERATE=4
NUMBER_ITERATION_SELECTION_COMPONENTE = 2
NUMBER_OF_CHILDREN_FOR_PARENTS= 2 # se negera 2 hijos por cadas dos padres
RESTRICTED_LIST_AMOUNT_COMPONENT = 2
SIZE_POPULATION = 2 # Tamaño de la poblacion final
INFINITE_POSITIVE = 100000000000000 
INFINITE_NEGATIVE = -100000000000000 
NUMBER_OBJECTIVE_AT_OBTIMIZATE = 4
#Results
PATH_RESULTS = "./dataset/results/"
